### ISSUE TITLE
Discord Portable adds itself to Add/Remove Programs

### ISSUE THREAD

**Issue by jyrkive** [portapps/discord-portable#10]
I thought I had the regular Discord still hanging there for some reason and went to uninstall it from there.

Then I found out it had actually uninstalled Discord from the folder of Discord Portable.

It might be that Discord only adds itself to Add/Remove Programs when it updates itself. I haven't monitored when exactly it appeared in the list.

**Comment by crazy-max** [comment]
Hi @jyrkive,

I was able to reproduce your issue. Adding to  Add/Remove Programs occurs when automatically updating Discord. I'll look to disable the automatic update.

**Comment by crazy-max** [comment]
Solved in latest release

**Comment by jyrkive** [comment]
Thanks! 👍
