### ISSUE TITLE
Windows Defender Flagged this as virus

### ISSUE THREAD

**Issue by Nyanpasu1** [portapps/discord-portable#101]
#### Steps to reproduce this issue

1. Install Discord Portable
2. Launch Discord Portable
3. Windows Defender automatically flagged the exe

#### Expected behaviour

> Should be working without any flag

#### Actual behaviour

> Flagged by Windows Defender

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 1.0.9010

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 11 64-bit

**Winver screenshot** : Edition	Windows 11 Home Single Language
Version	22H2
Installed on	‎08-‎Feb-‎23
OS build	22621.1194
Serial number	MP2BM9ZY
Experience	Windows Feature Experience Pack 1000.22638.1000.0

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/10215304/218610156-ffa1dbb6-7cd8-4731-acd9-4dfa28dc870f.png)

### Logs

No log available, since its fresh install

**Comment by crazy-max** [comment]
https://github.com/portapps/discord-portable/issues/46#issuecomment-688520503
