### ISSUE TITLE
Not really a portable application.

### ISSUE THREAD

**Issue by srg84** [portapps/discord-portable#11]
Hi,

This package is not really portable, when i format my pc, all settings and login information is erased and need to reconfigure all settings

**Comment by crazy-max** [comment]
Hi @srg84, can you send your log file ?

**Comment by srg84** [comment]
[00:00:00.000][PID   1048] Initializing overlay with binary path \\?\D:\DATOS\Programas\DiscordPortable\Data\AppData\discord\0.0.300\modules\discord_overlay2\2

[00:00:00.241][PID   1048] 

[00:00:00.488][PID   1048] 

[00:00:00.000][PID   8204] Initializing overlay with binary path \\?\D:\DATOS\Programas\DiscordPortable\Data\AppData\discord\0.0.300\modules\discord_overlay2\2

[00:00:00.245][PID   8204] 

[00:00:00.245][PID   8204] 

[00:00:00.000][PID   5000] Initializing overlay with binary path \\?\D:\DATOS\Programas\DiscordPortable\Data\AppData\discord\0.0.300\modules\discord_overlay2\2

[00:00:00.214][PID   5000] 

[00:00:00.214][PID   5000]

**Comment by srg84** [comment]
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules
[Modules] Module installed file path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\installed.json
[Modules] Module download path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending
[Modules] Bootstrapping...
[Modules] Installing discord_desktop_core@1 from D:\DATOS\Programas\DiscordPortable\App\Discord\app-0.0.300\resources\bootstrap\discord_desktop_core.zip
[Modules] Installing discord_erlpack@1 from D:\DATOS\Programas\DiscordPortable\App\Discord\app-0.0.300\resources\bootstrap\discord_erlpack.zip
[Modules] Installing discord_game_utils@1 from D:\DATOS\Programas\DiscordPortable\App\Discord\app-0.0.300\resources\bootstrap\discord_game_utils.zip
[Modules] Installing discord_overlay2@1 from D:\DATOS\Programas\DiscordPortable\App\Discord\app-0.0.300\resources\bootstrap\discord_overlay2.zip
[Modules] Installing discord_rpc@1 from D:\DATOS\Programas\DiscordPortable\App\Discord\app-0.0.300\resources\bootstrap\discord_rpc.zip
[Modules] Installing discord_utils@1 from D:\DATOS\Programas\DiscordPortable\App\Discord\app-0.0.300\resources\bootstrap\discord_utils.zip
[Modules] Installing discord_voice@1 from D:\DATOS\Programas\DiscordPortable\App\Discord\app-0.0.300\resources\bootstrap\discord_voice.zip
[Modules] Finished module installations. [success: 7] [failure: 0]
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] Module update available: discord_game_utils@2 [installed: 1]
[Modules] Module update available: discord_overlay2@2 [installed: 1]
[Modules] Module update available: discord_utils@2 [installed: 1]
[Modules] Module update available: discord_voice@2 [installed: 1]
[Modules] Fetching discord_game_utils@2 from https://discordapp.com/api/modules/stable/discord_game_utils/2
[Modules] Streaming discord_game_utils@2 [532979 bytes] to C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_game_utils-2.zip
[Modules] Fetching discord_overlay2@2 from https://discordapp.com/api/modules/stable/discord_overlay2/2
[Modules] Streaming discord_overlay2@2 [1638249 bytes] to C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_overlay2-2.zip
[Modules] Fetching discord_utils@2 from https://discordapp.com/api/modules/stable/discord_utils/2
[Modules] Streaming discord_utils@2 [521820 bytes] to C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_utils-2.zip
[Modules] Fetching discord_voice@2 from https://discordapp.com/api/modules/stable/discord_voice/2
[Modules] Streaming discord_voice@2 [5946078 bytes] to C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_voice-2.zip
[Modules] Finished module downloads. [success: 4] [failure: 0]
[Modules] Relaunching to install module updates...
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules
[Modules] Module installed file path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\installed.json
[Modules] Module download path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending
[Modules] Installing updates...
[Modules] Installing discord_game_utils@2 from C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_game_utils-2.zip
[Modules] Installing discord_overlay2@2 from C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_overlay2-2.zip
[Modules] Installing discord_utils@2 from C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_utils-2.zip
[Modules] Installing discord_voice@2 from C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_voice-2.zip
[Modules] Finished module installations. [success: 4] [failure: 0]
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
[Modules] Starting to install discord_spellcheck...
[Modules] Fetching discord_spellcheck@1 from https://discordapp.com/api/modules/stable/discord_spellcheck/1
[Modules] Streaming discord_spellcheck@1 [1887110 bytes] to C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_spellcheck-1.zip
[Modules] Finished module downloads. [success: 1] [failure: 0]
[Modules] Installing discord_spellcheck@1 from C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending\discord_spellcheck-1.zip
[Modules] Finished module installations. [success: 1] [failure: 0]
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules
[Modules] Module installed file path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\installed.json
[Modules] Module download path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules
[Modules] Module installed file path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\installed.json
[Modules] Module download path: C:\Users\Sergio\AppData\Roaming\discord\0.0.300\modules\pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.

**Comment by srg84** [comment]
Maybe some registry settings are outside the sandbox?

**Comment by crazy-max** [comment]
Hum your folder structure is not the same. Could you post a screenshot of this folder's content : `D:\DATOS\Programas\DiscordPortable` and `D:\DATOS\Programas\DiscordPortable\data`.
Thanks

**Comment by srg84** [comment]
Here:

https://imgur.com/a/MgbIY

Dunno why all settings are erased, i mean i see the link when discord portable is running on

"\AppData\Roaming\discord"

And unmounted when discord closes, maybe the program detect some Windows changes and reset itself?

**Comment by crazy-max** [comment]
The folder structure does not correspond to a portapps app.
It seems to be a PortableApps structure. Where do you download and install this portable app ?

This should be something like this :

![image](https://user-images.githubusercontent.com/1951866/36426283-db16e336-1649-11e8-99af-fb090d3b38f2.png)

**Comment by srg84** [comment]
Your the man!,

The problem was mi installation was corrupted, i tried deleting all, putting settings, formating windows.

And now all is stored.

Thank you, delete this and sorry for losing your time...

**Comment by crazy-max** [comment]
No problem ;)
