### ISSUE TITLE
Discord crashes when opening any server

### ISSUE THREAD

**Issue by KosMos-pv** [portapps/discord-portable#110]
### Behaviour
When I open any server Discord crashes and is unusable until I close it from tray. Sometimes it shows error "Color issues while screensharing" sometimes just general error with restart button.
#### Steps to reproduce this issue

1. Open any server
2. Wait few seconds
3. Discord shows error

#### Expected behaviour

I can see list of users and chat, join voice channels etc

#### Actual behaviour

Discord shows this error.
![image](https://github.com/portapps/discord-portable/assets/3979268/6a9cb3b9-caa2-4c15-9a00-45a4c04fa5bb)
But I have driver 536.99 (installed by Windows Update) so it's not an issue with NVIDIA.
On some servers Discord just shows error and restart button but when I press it Discord shows same error after restart and I have to close it from tray.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
Stable 240237 (a1ba594)
Host 1.0.9010

**Operating system (ex. Windows 10 Pro 64 bits)** :
Windows 10 Pro
**Winver screenshot** :
![image](https://github.com/portapps/discord-portable/assets/3979268/f5bb5b91-f3f3-4bad-87bb-f32359504d6d)

### Logs

[discord-portable.log](https://github.com/portapps/discord-portable/files/13163585/discord-portable.log)

**Comment by B-eT-a** [comment]
i also have the same issue.
seems like Discord Portable needs a Update to the latest version.

best regards :)

**Comment by ErikExoteric** [comment]
Same issue here, [might be a similar issue to last year](https://github.com/portapps/discord-portable/issues/96#issuecomment-1321117798) with Discord Portable probably needing to update the Host Version to the latest one. I don't have the Official Desktop client installed but _hopefully that's the fix again_

**Comment by wazerstar** [comment]
Can confirm, its crashing all the time, chat content going missing and who's on the server to the right cannot be seen.

@crazy-max we need an update as soon as possible

**Comment by jfl-aw** [comment]
On my end f I don't press right click it won't crash. Other than that no notifications are shown, can't see who's part of the server and some other small nuisances.

**Comment by starfishpatkhoo** [comment]
Happens to me too sadly.. 😬 Windows 11 ...

**Comment by carrotice** [comment]
I don't have an NVIDIA graphics card but I have the same error.

Discord: 1.0.9010-15 win32
Portapps: 3.7.0
OS: Win 10 Pro 22H2 build 19045.3570

![Discord_error_NVIDIA](https://github.com/portapps/discord-portable/assets/87601284/782f39d1-efc2-4f30-8e21-591104820e18)

**Comment by wharlox** [comment]
well i accidentally pushed an MR to this repo (vs first my own fork) - https://github.com/portapps/discord-portable/pull/111 


but so far i have not got the color-issues warning (and im also not on the latest version of nvidia mentioned in the error), nor the crash-loop.

**Comment by MrxHellsing** [comment]
![image](https://github.com/portapps/discord-portable/assets/29206412/4e04a5f7-66dc-4f0c-9c41-c649dc6c5721)
normally, there are 15-20 people here, but now, for the past few days, nothing has been showing, can't send any messages to anyone. The app immediately crashes or closes down if I try.

**Comment by Bunnnyface** [comment]
Hi everyone.
No color bug but actualization issue here, with last release on W10 22H2
Discord portapps crashes and needs to refresh when selecting emojis and doesn't send message.

![discord portapps](https://github.com/portapps/discord-portable/assets/132709546/80cdb051-8deb-4abb-9ced-763ca68802c7)

**Comment by Abalieno** [comment]
I'll try a second summon attempt @crazy-max 
The dev seems very much active, it could be he missed the problem here somehow...

**Comment by ms-dc** [comment]
Yeah everything seems kinda broken right now. I choose/switch server, stops working. I choose/switch channel, stops working as well

**Comment by dystopia2017** [comment]
Same issue here, It crashed within 10 seconds of opening. :(
having to use discord it in a portable browser until it's fixed.

**Comment by peterpekkanen** [comment]
Hi.

I also got the same issue as above. Started last week as the halloween event started on Discord and havent been able to run it properly since then without crashing. Previously I've had no issues with Discord Portable.

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19045 Build 19045

**Comment by DjDiabolik** [comment]
Hi boys......... i don't have understand correctly how i need to do.
Currently i have ever use the current portable from here:
https://portapps.io/app/discord-portable/#download

Recently the app it's become unusable...... it's all like running at very slow and the app it is generally non-functional.

How i need to do ? If i understand correctly upper here it's will need to be updated to 1.0.9020........... but how i can do this ?
the @wharlox mirror it's fix this issue ? How i can update that ?

**Comment by hitman72ita** [comment]
in the best case scenario, at each new start, the update starts again, it make again folder 1.0.9010 and the deletes it again... for the moment I am using another portable cliemt

**Comment by ms-dc** [comment]
> in the best case scenario, at each new start, the update starts again, it make again folder 1.0.9010 and the deletes it again... for the moment I am using another portable client

may I ask the other client you are using now?

**Comment by hitman72ita** [comment]
search for "dorion sourceforge". 2 updates in these last days. but I will go back to discord-portable as soon as it is working

**Comment by wazerstar** [comment]
> search for "dorion sourceforge". 2 updates in these last days. but I will go back to discord-portable as soon as it is working

no need its found here

https://github.com/SpikeHD/Dorion

**Comment by ms-dc** [comment]
thank you guys, I'll use that one until this one gets an update as well
