### ISSUE TITLE
Blank Icon

### ISSUE THREAD

**Issue by MrCharisma** [portapps/discord-portable#12]
Issue:
When launching Discord the icon is blank and is not using the correct Icon.

![capture](https://user-images.githubusercontent.com/32368259/44388621-78431980-a520-11e8-8003-a0452d6245e5.PNG)

**Comment by crazy-max** [comment]
Hi @jamiestinson05 can you follow the SUPPORT.md page please? Thanks :)
And i think it's related to portapps/slack-portable#12

**Comment by jamiestinson05** [comment]
Issue:
When launching Discord the icon is blank and is not using the correct Icon.

Configuration:
0.0.301-23 win32

Windows 10 Home 64 Bit
![image](https://user-images.githubusercontent.com/32368259/44389159-010e8500-a522-11e8-9a41-39f804aa1184.png)

Logs:
[discord-portable.log](https://github.com/portapps/discord-portable/files/2305366/discord-portable.log)

@crazy-max I also tried copying app/app.ico to app/app-win10.ico this did not resolve the issue.

**Comment by crazy-max** [comment]
Ok thanks i keep you in touch

**Comment by crazy-max** [comment]
Can you post a screenshot of the content of `discord-portable/data` please ?

**Comment by MrCharisma** [comment]
@crazy-max Forgot to reply to this, issue was resolved about a week ago. Not sure how a fix occurred I moved the folder from the C drive to another drive and the issue was resolved.
