### ISSUE TITLE
64 bit version?

### ISSUE THREAD

**Issue by djsolidsnake86** [portapps/discord-portable#120]
is possible create a 64bit version portable? thanks

**Comment by NextWork123** [comment]
i tried but it was running to 32bit so i hope they can do that

**Comment by crazy-max** [comment]
Discord does not provide 64-bit of its app afaik.

**Comment by NextWork123** [comment]
> Discord does not provide 64-bit arch of its app afaik.

Actually, Discord does provide a 64-bit version of its application. I am currently using Vencord, but I can confirm that Discord uses x64. Please ensure the accuracy of the information next time.
![immagine](https://github.com/user-attachments/assets/c760c595-1c75-4f99-bca1-fc84c326f34a)

**Comment by crazy-max** [comment]
> Please ensure the accuracy of the information next time.

That's why I said afaik but glad to see 64-bit is available. Will make some changes for this.
