### ISSUE TITLE
How to disable updates and install old discord?

### ISSUE THREAD

**Issue by lynrayy** [portapps/discord-portable#123]
How to disable updates and install old discord?

**Comment by lynrayy** [comment]
Re open
https://github.com/portapps/discord-portable/issues/75

**Comment by crazy-max** [comment]
It should not auto update as we pin the core modules: https://github.com/portapps/discord-portable/blob/master/res/pinned_update.json

If discord is updated on your side then open a [bug report](https://github.com/portapps/discord-portable/issues/new?assignees=&labels=&projects=&template=bug_report.md). Thanks.
