### ISSUE TITLE
Discord Portable creates a shortcut in start menu on launch

### ISSUE THREAD

**Issue by neodyne** [portapps/discord-portable#13]
Using the latest `discord-portable-win32-0.0.301-24-setup.exe`, fully updated, on Windows 10 x64 v1809. No other instances of Discord installed.

Each time the app is run (from `discord-portable.exe`), it creates a shortcut to the main executable (not the wrapper) in start menu. This can also be seen when inspecting `discord-portable.log`:

`INFO : 2018/12/06 01:52:13.326320 main.go:51: --------`
`INFO : 2018/12/06 01:52:13.383700 main.go:52: Starting Discord...`
`INFO : 2018/12/06 01:52:13.383700 main.go:53: Current path: D:\discord_portable`
`INFO : 2018/12/06 01:52:13.383700 sys.go:197: Create folder D:\discord_portable\data...`
`INFO : 2018/12/06 01:52:13.384359 electron.go:10: Lookup app folder in: D:\discord_portable\app`
`INFO : 2018/12/06 01:52:13.384359 electron.go:14: Electron app folder found: app-0.0.301`
**`INFO : 2018/12/06 01:52:13.392847 sys.go:37: Create shortcut for D:\discord_portable\app\app-0.0.301\Discord.exe in C:\Users\xxxx\AppData\Roaming/Microsoft/Windows/Start Menu/Programs/Discord Portable.lnk...`**
`INFO : 2018/12/06 01:52:13.531733 exec.go:29: Process: D:\discord_portable\app\app-0.0.301\Discord.exe`
`INFO : 2018/12/06 01:52:13.531733 exec.go:30: Args:  `
`INFO : 2018/12/06 01:52:13.531733 exec.go:31: Working dir: D:\discord_portable\app\app-0.0.301`
`INFO : 2018/12/06 01:52:13.531733 exec.go:32: Data path: D:\discord_portable\data`
`INFO : 2018/12/06 01:52:13.531733 exec.go:34: Launch Discord...`
`INFO : 2018/12/06 01:52:13.531733 exec.go:41: Exec D:\discord_portable\app\app-0.0.301\Discord.exe  `

If another shortcut with the same name already exists (pointing elsewhere), it is replaced with the one above. This may be general electron behavior, as it occasionally happens with another electron-based application made portable (Streamlink Twitch GUI), but not on every launch. If this is intentional, it defeats the purpose of the app being portable, as it leaves unnecessary shortcuts, especially not to the wrapper, but the main executable.

**Comment by crazy-max** [comment]
@neodyne This behavior was introduced by rocketchat-portable/issues#3 :

> On Windows 8 / 10, notifications are made through an [Application User Model ID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459(v=vs.85).aspx) with [Electron](https://electronjs.org/docs/tutorial/notifications#windows). A shortcut to the application must be added in the start menu to make dekstop notifications working.

> For the moment we use the default shortcut created by Squirrel and we override the target path because I cannot handle `appUserModelId` and `toastActivatorCLSID` properties. More info on [Squirrel repository](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.ApplyReleases.cs#L242-L246).

We could remove the shortcut on close for example. What do you think ?

**Comment by neodyne** [comment]
Good to know! By the way, this may be relevant to Discord PTB as well.

**Comment by crazy-max** [comment]
Yes indeed and others Portapp based on Electron too. I will push an update asap, thanks for your input

**Comment by crazy-max** [comment]
Should be fixed now
