### ISSUE TITLE
Discord Create a Shortcut in my Programs List

### ISSUE THREAD

**Issue by Machou** [portapps/discord-portable#14]
Hi :)

When I launch **Discord**, the latest version (_0.0.304-27_), it creates a shortcut in the list of my programs.

Apparently the bug has been "fixed" in version _0.0.301-25_, but unfortunately, but not for me anyway :P, I am on **Windows 7 - 64 bit French version**.

This is a screenshot : https://i.ibb.co/HqDGBXs/Screenshot-Discord-Portable.jpg

Is it possible to fix this bug that has been going on for a few versions now? :D

Thank you for all the work you do anyway.

Regards,
Machou

**Comment by crazy-max** [comment]
Hi @Machou, the shortcut will be deleted when Discord is closed.

**Comment by Machou** [comment]
Not for me ^^
