### ISSUE TITLE
settings issue

### ISSUE THREAD

**Issue by patrickdrd** [portapps/discord-portable#15]
hello,
IMO the user files and settings should be stored outside the app folder
(like paf are doing),
because I updated today and I missed my login, settings, etc,
are the settings retained at least?
I can't check now, because I don't have access to discord servers at work,
but I would like to check if it's "start with windows" setting is disabled as I set it to in the previous installation,

also, can the individual modules be disabled somehow?
I mean I don't want the updater to run each and every time I open the app (that's why I can't open the app now), I'm updating manually, can I disable it somehow?

**Comment by crazy-max** [comment]
Hello @patrickdrd !
User files are already stored outside the `app` folder (in `data` folder).
From which version have you upgraded?
Also yes "start with Windows" is disabled but we can add a setting param for this.
Can you post your log file and follow the "reporting an issue" page please : https://portapps.io/doc/reporting-issue/

**Comment by patrickdrd** [comment]
actually the user files weren't there for me, I've also noticed that I had to login each time I opened the app with the latest version, I updated from 0.305 
start with Windows was enabled after updating as well and I had to disable it 
I waited a while for you to answer but yesterday I installed another portable from someone else, I don't remember and I updated the core files and everything works fine
