### ISSUE TITLE
Updating on starting

### ISSUE THREAD

**Issue by nmhung1985** [portapps/discord-portable#16]
When starting the program, it shows "Updating 1 of 5...". Is this normal and the automatic update is still disabled, or is this a bug?

I'm using the 305-1 version on Win 10 1607.

**Comment by crazy-max** [comment]
Yes, some Discord modules are updated automatically. This is why Portapps does not often deliver versions of Discord. Only the [major versions provided by Discord](https://discordapp.com/api/updates/stable?platform=win) are available for download on [portapps.io](https://portapps.io/).
