### ISSUE TITLE
Appdata/Roaming/Discord folder still created for logs

### ISSUE THREAD

**Issue by Forceflow** [portapps/discord-portable#17]
Install the latest discord-portable. Notice how on app startup the folder C:\Users\(username)\AppData\Roaming\Discord\logs is still created. Empty, but there :)

Not a huge issue, of course, just thought I'd report through the proper channels.

Tested with 0.0.305 release.

**Comment by crazy-max** [comment]
@Forceflow Yes this is a [known issue](https://github.com/portapps/franz-portable/issues/3) with Electron based apps unfortunately. Will try to get around that. Anyway thanks for your feedback :)

**Comment by Forceflow** [comment]
I suspected as much. Ah well, it's definitely not a huge issue, but I thought it could indicate more data leakage in the future.

**Comment by crazy-max** [comment]
Yes and looks like it's solved since Electron 6.

**Comment by crazy-max** [comment]
@Forceflow This has been fixed through a opt-in `cleanup` config parameter. See Configuration section in https://portapps.io/app/discord-portable/#infos for more info.
