### ISSUE TITLE
Blank Grey Window

### ISSUE THREAD

**Issue by jashoewa** [portapps/discord-portable#18]
### Behaviour

On launch a maximized grey window is open for a few seconds. I added --start-minimized to the discord-portable.yml file since I launch the program on startup from the Windows 10 task scheduler.

[discord-portable.yml.txt](https://github.com/portapps/discord-portable/files/3731814/discord-portable.yml.txt) (renamed to .txt for upload)

#### Steps to reproduce this issue

1. Open Discord_Portable.exe
2. Deleted contents of the Cache folder with no change.
3. Disabled cache with the following steps. Hold CTL+SHIFT+I > go to the network tab and disable cache then restart Discord Portable.

#### Expected behavior

> Discord should start completely in the background with no window popping up. Especially not a blank grey window.

#### Actual behaviour

> Blank grey maximized window comes up for a few seconds then disappears on the launch of the program.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :  win32-0.0.305-1

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro 64bit

**Winver screenshot** :

> 
![image](https://user-images.githubusercontent.com/51926214/66877245-c320bb80-ef82-11e9-8024-e4cbfdaa854c.png)

### Screenshots

> 
![image](https://user-images.githubusercontent.com/51926214/66877673-632b1480-ef84-11e9-92f7-954a2ef83cdf.png)

### Logs

[discord-portable.log](https://github.com/portapps/discord-portable/files/3731807/discord-portable.log)

**Comment by crazy-max** [comment]
Hi @jashoewa,

It's an upstream issue from Discord, nothing to do with Portapps. I suggest to [contact them](https://support.discordapp.com/hc/en-us/articles/115000465492-How-to-Report-Bugs) to fix this. See also https://www.reddit.com/r/discordapp/comments/8ov1uy/discord_grey_screen_problem/

Anyway thanks for your report!
