### ISSUE TITLE
How do you install

### ISSUE THREAD

**Issue by Blue2689** [portapps/discord-portable#28]
#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
https://portapps.io/app/discord-portable/#installation
