### ISSUE TITLE
McAfee detects virus

### ISSUE THREAD

**Issue by git-nico** [portapps/discord-portable#46]
Would love to use your portable apps but I cant use the latest version because McAfee thinks it contains a virus.
Version 0.0.305 does not have that issue.
I hope something can be done about it. I have similar issues with brave-portable.
![discord-virus-detectie](https://user-images.githubusercontent.com/51365811/92417789-55feb180-f164-11ea-9d4e-f933ac52cbb2.png)

**Comment by crazy-max** [comment]
@git-nico Sometimes Antivirus scanner reports that a program is infected with a Virus or Trojan, even when the program is not really infected with any malicious code. This kind of problem is known as "False Positive". In other words, [Antivirus companies cause a big headache to small developers](http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/).

As stipulated in the [FAQ](https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper), those detections are generic. Most likely based on a heuristic detection and more prone to be false-positive and this [happens quite often](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20antivirus) with programs written in [Golang](https://golang.org/). The best you can do is to report this to your Antivirus software vendor as a false positive.

See also portapps/portapps#68 and https://github.com/search?q=org%3Aportapps+antivirus&type=Issues. Thanks for your support.
