### ISSUE TITLE
RTC Connecting issue

### ISSUE THREAD

**Issue by infide1** [portapps/discord-portable#49]
After latest update, voice chat cannot be initiated.
RTC Connecting remains on the bottom left.
Official release works on same pc with same discord account

**Comment by crazy-max** [comment]
@infide1 Cannot reproduce your issue, it's working for me:

![image](https://user-images.githubusercontent.com/1951866/94595019-c25b6500-0279-11eb-8282-e5ce1d577249.png)

Does it work with the previous release? (0.0.307-5). Also please create a [proper bug report](https://portapps.io/doc/reporting-issue/).

**Comment by infide1** [comment]
Sorry for the incomplete report. The update must have failed somehow. My discord portable folder\app had 2 folders inside
app-0.0.305 and app-0.0.308. it appears the update somehow failed to delete app-0.0.305 and i was running 305

**Comment by crazy-max** [comment]
Ok thanks for your input, I will take a look about the deletion issue
