### ISSUE TITLE
Cleanup force should delete "C:\Users\Username\AppData\Local\Temp\Discord Crashes"

### ISSUE THREAD

**Issue by mdfazlerabbi145** [portapps/discord-portable#51]
There is a log folder in the temp directory which leaves traces.

Cleanup force parameter should delete this: "C:\Users\Username\AppData\Local\Temp\Discord Crashes"

## 

* Portapps 1.31.0
**App release** : 0.0.305-2 (2019/12/15)

**Operating system** : Windows 10 Pro 64 bits

**Comment by crazy-max** [comment]
@mdfazlerabbi145 LGTM, thanks for your input.

**Comment by thegreatestminer** [comment]
Should be `%TEMP%\Discord Crashes`.

**Comment by Chaython** [comment]
Should put it in the portable data folder or disable crash logging...

**Comment by crazy-max** [comment]
Should be fixed with latest release: https://portapps.io/app/discord-portable/#download
