### ISSUE TITLE
Unable to run discord-portable.exe as administrator.

### ISSUE THREAD

**Issue by ezonius** [portapps/discord-portable#56]
![image](https://user-images.githubusercontent.com/61872098/103158849-de13d000-47c2-11eb-84a6-25ee9f2c0542.png)

Happens on Windows 10. Runs just fine without trying to run as administrator, but running Discord as admin is needed if you use push-to-talk and other apps are running as administrator.

There is nothing in the log.

**Comment by crazy-max** [comment]
Should be fixed with latest release: https://portapps.io/app/discord-portable/#download
