### ISSUE TITLE
Support simultaneous multi-instance (feature request)

### ISSUE THREAD

**Issue by GnstheGrain** [portapps/discord-portable#6]
***Feature description/purpose:***
_Support running multiple instances simultaneously, allowing user to use as many Discord Account/IDs at once._

   
#### Steps to reproduce this ~issue~ unimplemented feature
1. Launch discord-portable.exe
2. Launch discord-portable.exe (2nd instance)
3. Launch discord-portable.exe (3rd instance)
4. [...]

   
#### Actual behaviour
Launching each of those redirect to (reopen) the current running instance.

#### Expected behaviour
*   Each launched instance should execute as a single separate "discord-portable.exe" process
(Many portable tools offers such multi-instance feature by implementing an optional switch for the user to launch from. ie. `$ discord-portable.exe {-p|m}`
*   Each instance should not only be allowed to run seperately, but let the user to log into distinct Discord ID/Accounts as well.)
*    _(Optional, but preferable)_ Each instance should be contained/isolated _(if required)_ , in order to prevent both of any Account/Machine-lvl -UUID correlation from being performed/detect from Discord's servers. (if any such thing appears to be existing in the code)..  for instance: I've notice the `Preferences` file to use the _(now depreciated)_ brightray library, (which I assume stem from the Electron repacking/wrapping process): `{"brightray":{"media":{"device_id_salt":"<SALTHASH>"}}}`
(However, I know close to nothing about Electrum, so this brightray code could very well be only used by Electrum to properly bound the repacked app with the target machine, hence, not necessarily used/fetched in any way by/to discord's servers.) This however remains unverified.. it would require some research and/or audit to confirm. (some basic-yet-rigorous traffic analysis would make it).

**Discord portable version** :
v0.0.298-13

**Comment by crazy-max** [comment]
@GnstheGrain I will take a look on this feature, i keep you in touch.

**Comment by crazy-max** [comment]
Hi @GnstheGrain, i've worked on this feature and it will be available in the next release ;)

**Comment by crazy-max** [comment]
Implemented in latest release : https://github.com/portapps/discord-portable/releases/tag/0.0.300-19
For your last point about machine id, open a new issue please.
