### ISSUE TITLE
You absolutely cannot get this thing off your PC

### ISSUE THREAD

**Issue by HolyPeanut** [portapps/discord-portable#61]
Once you've plugged in the USB and used discord through it it sticks around as your discord's shortcut and EXE without any way to remove it, not through deleting discord, not in regedit, nothing. Hell, this thing's so persistent you could call it a virus, all i want is a way to remove the .ink/.exe that comes with this, so i can have discord launch with it's own icon

**Comment by crazy-max** [comment]
Then create a [bug report](https://github.com/portapps/discord-portable/issues/new?assignees=&labels=&template=bug_report.md), thanks.
