### ISSUE TITLE
Infinity crash on windows 10

### ISSUE THREAD

**Issue by hldh214** [portapps/discord-portable#62]
#### Steps to reproduce this issue

1. Start discord-portable.exe

#### Expected behaviour

App run normally

#### Actual behaviour

Infinity crash and restart the app

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : discord-portable-win32-0.0.309-7-setup.exe

**Operating system (ex. Windows 10 Pro 64 bits)** : windows 10 (17763.1790)

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/5501843/110487397-81b91f00-8128-11eb-927a-c06ac677d8af.png)

### Screenshots

None.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

[discord-portable.log](https://github.com/portapps/discord-portable/files/6109259/discord-portable.log)

**Comment by hldh214** [comment]
![image](https://user-images.githubusercontent.com/5501843/110495736-c1cfd000-812f-11eb-892c-7f1ff705fdf5.png)
Things happened even switching to the English display language.

**Comment by crazy-max** [comment]
@hldh214 Thanks for your feedback. Do you have the same issue with the regular discord setup? : https://github.com/portapps/discord-portable/releases/download/0.0.309-7/DiscordSetup-win32.exe

**Comment by hldh214** [comment]
> @hldh214 Thanks for your feedback. Do you have the same issue with the regular discord setup? : https://github.com/portapps/discord-portable/releases/download/0.0.309-7/DiscordSetup-win32.exe

Indeed... So that's not an issue w/ this project. I'll submit a ticket to their support team. Thanks for the help~
