### ISSUE TITLE
[Suggestion] BetterDiscord Support

### ISSUE THREAD

**Issue by Fundryi** [portapps/discord-portable#63]
Would be really cool if a BD could be supported somehow x)
Didn't manage to get it work, whenever I would start Portable Discord with BD installed it would give me an error.
It adds several options for custom-made content like Themes and Plugins.

https://betterdiscord.net/home/
https://github.com/jiiks/betterdiscordapp

Regards

**Comment by crazy-max** [comment]
@Fundryi BetterDiscord is outdated and not compatible anymore with Discord. BandagedBD is another one but not compatible with portable discord. See https://github.com/portapps/discord-ptb-portable/issues/29#issuecomment-751399940.

**Comment by Fundryi** [comment]
I see no support, alright :,(

**Comment by sh1ft-github** [comment]
Do you by any chance know the last supported version of Discord Portable that worked with BetterDiscord? I could just install an older version since you offer them on your website.

**Comment by sh1ft-github** [comment]
Do you by any chance know the last supported version of Discord Portable that worked with BetterDiscord? I could just install an older version since you offer them on your website.


> 
> 
> @Fundryi BetterDiscord is outdated and not compatible anymore with Discord. BandagedBD is another one but not compatible with portable discord. See [portapps/discord-ptb-portable#29 (comment)](https://github.com/portapps/discord-ptb-portable/issues/29#issuecomment-751399940).

**Comment by Fundryi** [comment]
> 
> 
> Do you by any chance know the last supported version of Discord Portable that worked with BetterDiscord? I could just install an older version since you offer them on your website.
> 
> > @Fundryi BetterDiscord is outdated and not compatible anymore with Discord. BandagedBD is another one but not compatible with portable discord. See [portapps/discord-ptb-portable#29 (comment)](https://github.com/portapps/discord-ptb-portable/issues/29#issuecomment-751399940).

https://github.com/rauenzi/BetterDiscordApp
That's the one I'm Using with CanaryDiscord. Working fine for me x)
