### ISSUE TITLE
Viruses in release files?

### ISSUE THREAD

**Issue by JeffHoogland** [portapps/discord-portable#64]
On the release downloads page there are viruses listed in your installer file according to a scan it looks like GitHub does?

discord-portable-win32.exe is the file in question.

Report the GitHub tool generated here: https://www.virustotal.com/gui/file/91d46ae0c74129ea17230da62a8443ae6c8d29bd98171b852301918bd3147947/detection

**Comment by crazy-max** [comment]
@JeffHoogland https://github.com/portapps/discord-portable/issues/46#issuecomment-688520503
