### ISSUE TITLE
JavaScript error after proceeding with the installation of BetterDiscord for both latest versions

### ISSUE THREAD

**Issue by sh1ft-github** [portapps/discord-portable#66]
#### Steps to reproduce this issue

1. Download both latest versions of Discord Portable and BetterDiscord
2. Install Discord Portable
3. Install BetterDiscord
4. _THE ERROR_

#### Expected behaviour

> I would like to install BetterDiscord alongside Discord Portable. After installing BetterDiscord I expect Discord Portable to be normally usable with BetterDiscord working.

#### Actual behaviour

> Instead right after installing BetterDiscord a JavaScript errors comes up and Discord Portable becomes unusable.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro 64 bits

**Winver screenshot** :

> ![Capture](https://user-images.githubusercontent.com/71072643/114940900-f8d18980-9e31-11eb-9bf0-13c91b75cd08.png)

### Screenshots

> ![Capture](https://user-images.githubusercontent.com/71072643/114941271-74cbd180-9e32-11eb-94d5-c1143cb63954.png)

### Logs

[discord-portable.log](https://github.com/portapps/discord-portable/files/6321252/discord-portable.log)

**Comment by crazy-max** [comment]
@sh1ft-github https://github.com/portapps/discord-portable/issues/63#issuecomment-799416159
