### ISSUE TITLE
Discord 1.0.9001

### ISSUE THREAD

**Issue by Chaython** [portapps/discord-portable#67]
Update for 1.0.9001
Previous updates, the internal updater, worked as portable, but with this newest discord update, the portapps launcher will launch the older version of discord, and despite 1.0.9001 installing to the portable folder, it puts all appdata in roaming etc.

[discord-portable.log](https://github.com/portapps/discord-portable/files/6389615/discord-portable.log)

**Comment by crazy-max** [comment]
@Chaython Thanks for your feedback. Looks like main module has been updated from 0.0.309 to 1.0.9001 cilently. We'll make the update soon. Keep you in touch.

**Comment by shojimeguro** [comment]
this is also happened to me, so for now i cannot update it until this is fixed

**Comment by maxstlk** [comment]
> 
> 
> @Chaython Thanks for your feedback. Looks like main module has been updated from 0.0.309 to 1.0.9001 silently. We'll make the update soon. Keep you in touch.

Sorry to bother, but you, probably, forgot about it =)

**Comment by crazy-max** [comment]
Working on it guys. I have two issues with v1.x.x of Discord atm:

* [x] Handle `installer.db` to be able to manage versioning without crashing portable
* [ ] Skip host update

I have managed to fix the first issue last week. Needs to fix the last one and will be good to create a release.

**Comment by crazy-max** [comment]
@maxstlk 

> Sorry to bother, but you, probably, forgot about it =)

I've got an enhanced dashboard to handle all my backlog across GitHub with priorities so no I'm aware of this but I've got many projects to maintain. So please be patient or contribute. Thanks.

**Comment by Zealest** [comment]
> @maxstlk
> 
> > Sorry to bother, but you, probably, forgot about it =)
> 
> I've got an enhanced dashboard to handle all my backlog across GitHub with priorities so no I'm aware of this but I've got many projects to maintain. So please be patient or contribute. Thanks.

No problem man, take your time!

**Comment by fahmiyufrizal** [comment]
Take ur time and do ur best, man!
We'll waiting, ur project helped a lot of internet cafe here!

**Comment by crazy-max** [comment]
Using a pinned manifest to "disable" auto-update seems to work for now. Can you try https://github.com/portapps/discord-portable/releases/tag/1.0.9002-9? Thx.

**Comment by fahmiyufrizal** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/60032856/131682205-025dd4a9-ebe2-4581-95b9-31b663b07799.png)
Is it normal to update it?

**Comment by crazy-max** [comment]
@fahmiyufrizal 

> Is it normal to update it?

Yes this is just the modules not host update (aka core).

**Comment by crazy-max** [comment]
@fahmiyufrizal Great, let's wait for the next iteration (1.0.9003) to see if pinned manifest still works.

**Comment by crazy-max** [comment]
https://portapps.io/app/discord-portable/#download

**Comment by DodoGames7** [comment]
1.0.9003 is here now
