### ISSUE TITLE
Is it possible to block Discord Portable to auto-update?

### ISSUE THREAD

**Issue by SixelAlexiS90** [portapps/discord-portable#75]
Hello, I want to know if I can avoid to let the Portable Discord got from your site to got updated to the latest version.

I ask since one of the latest versions of Discord has a bug with Mic Test and I need to use that function for something else.
Thanks :)

**Comment by crazy-max** [comment]
See https://github.com/portapps/discord-portable/issues/67#issuecomment-859152721

**Comment by lynrayy** [comment]
+??
