### ISSUE TITLE
How do I manually build this software?

### ISSUE THREAD

**Issue by Austcool-Walker** [portapps/discord-portable#77]
Hi I noticed you basically built discord app for 32bit windows 7+ I want to use this project for building the discord app for many unsupported platforms. Would you mind sharing how to build this so I can build this for other types of computers? Like the Commands issued during the electron build process? If you could I'd be grateful!

**Comment by crazy-max** [comment]
Discord only provides win 32bits binary. Link can be seen [here](https://github.com/portapps/discord-portable/blob/c676e05c27675929f0987e0974821ae5dcd26847/build.properties#L40).
