### ISSUE TITLE
Crash on logging

### ISSUE THREAD

**Issue by Mitch037** [portapps/discord-portable#78]
When I'm trying to log into Discord it crashes. Here's a piece of the log file:

> Discord 1.0.9003
> Starting app.
> Starting updater.
> [WebContents] crashed (crashed)... reloading
> [WebContents] double crashed (crashed)... RIP =(
C:/Users/runneradmin/go/pkg/mod/github.com/portapps/portapps/v3@v3.3.1/portapps.go:211 > Closing Discord

**Comment by Rinat84** [comment]
Помогает discord-portable.yml
```
common:
  disable_log: true
```

**Comment by Mitch037** [comment]
> Помогает discord-portable.yml
> 
> ```
> common:
>   disable_log: true
> ```

Now it's working fine. Thank you!
