### ISSUE TITLE
New BetterDiscord2 is not working on 1.0.9003 whereas works fine on 9002

### ISSUE THREAD

**Issue by nulledone** [portapps/discord-portable#79]
Here's the error;
![1](https://user-images.githubusercontent.com/29547468/140010075-623d0b8a-ef53-43e0-b5ca-bac3c8ce28e0.png)

I've also checked following, however still wanted to point out the issue since BetterDiscord is now an active project;
https://github.com/portapps/discord-portable/issues/66
https://github.com/portapps/discord-portable/issues/63#issuecomment-799416159

**Comment by crazy-max** [comment]
Sorry we don't bring support for BetterDiscord but feel free to contribute if you want that to be fixed here.
