### ISSUE TITLE
After reformat my settings is lost

### ISSUE THREAD

**Issue by wazerstar** [portapps/discord-portable#8]
Hello I dont think this is really an issue but, would be really nice feature to be allowed to save appdata settings into the portable folder, or make it read from manually entry creating the files for it?

**Comment by crazy-max** [comment]
Hi,

Yes it's an issue, can you follow [those steps](https://github.com/portapps/discord-portable/blob/master/.github/SUPPORT.md) to create your issue please ?
And can you post the structure of your discord-portable folder also ?

**Comment by wazerstar** [comment]
I cannot provide you info since I did a clean state of the portable installation now, so you wont get any info from that, But I can assure you the structure was like the portable installation or zip at that time I downloaded was unchanged, we talk maybe last year around mid 2017 or oct release.

**Comment by crazy-max** [comment]
Ok and after you format your computer, you copy back the `discord-portable` folder on your new system right ?

**Comment by wazerstar** [comment]
I had the entire folder on another drive which was never touched or moved in Any way, even the secondary drive was assigned as e: before and after the format.

**Comment by crazy-max** [comment]
Ok this is a strange issue. Do you have your old `discord-portable.log` maybe ?

**Comment by wazerstar** [comment]
No sorry nothing leftovers I removed the entire folder

**Comment by crazy-max** [comment]
Ok keep me in touch if you have a similar issue next time
