### ISSUE TITLE
Updater infinitely tries to update

### ISSUE THREAD

**Issue by Kingminer7** [portapps/discord-portable#90]
I can't get into Discord because the updater doesn't work for me.

**Comment by itsonlybarney** [comment]
I'm having an issue where Discord Portable tries to check for updates on first launch and gets stuck in a continual loop trying to do so.  This occurs both using the setup executable, and extracting from the 7z file.
![DiscordPortable_Update on Launch](https://user-images.githubusercontent.com/616622/167341290-1fc4d245-0a34-485f-9aec-9bf9ea8d2e2e.png)
