### ISSUE TITLE
RTC Connection yellow since 19-11-2022 - using normal discord installation or web works fine.

### ISSUE THREAD

**Issue by wazerstar** [portapps/discord-portable#96]
#### Steps to reproduce this issue

1. Download Latest version you guys have made in portable,
2. Connect to a discord room.
3. Check the connection as show in this picture https://i.imgur.com/2JOKXYN.png

#### Expected behaviour

> Should be able to talk with others

#### Actual behaviour

> Cannot talk to others, it states yellow RTC Conneciton, you can join channels but nobody can hear you, nor can you talk to them. I tried with clean installation of the portable capture, no luck

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 

[1.0.9006-13](https://github.com/portapps/discord-portable/releases/tag/1.0.9006-13)

**Operating system (ex. Windows 10 Pro 64 bits)** : 

Windows 10 Pro x64

**Winver screenshot** : 

https://i.imgur.com/5RYUy4H.png

### Logs

Join the log file `log\[appname]-portable.log` to this issue.
[discord-portable.log](https://github.com/portapps/discord-portable/files/10048390/discord-portable.log)

**Comment by ErikExoteric** [comment]
I have the same problem too. I have a wild guess about it but it might be due to the current Host version for the Desktop Client being 1.0.900**7** while Discord Portable having 1.0.900**6**.

I've done the whole `flushdns` thing and the people have said all over the net as well as clearing the cache + deleting my own copy of Discord portable and reinstalling it on a different drive yet the problem persists.

**Comment by 99stem** [comment]
> I have the same problem too. I have a wild guess about it but it might be due to the current Host version for the Desktop Client being 1.0.900**7** while Discord Portable having 1.0.900**6**.
> 
> I've done the whole `flushdns` thing and the people have said all over the net as well as clearing the cache + deleting my own copy of Discord portable and reinstalling it on a different drive yet the problem persists.

Can confirm.
I manually updated the portable version to the latest (1.0.9007), and it works now.
